### ISSUE TITLE
Data Alignment may have error?

### ISSUE THREAD

**Issue by bfdyanshe** [ashvardanian/BenchmarkingTutorial#1]
The loop in *f32_pairwise_accumulation* have `f32s_in_cache_line_half_k` * 2 times, and the other one only have `f32s_in_cache_line_half_k` times.
![图片](https://github.com/user-attachments/assets/ad7a0374-48a2-409d-aaf8-5549c664bc48)

**Comment by ashvardanian** [comment]
@bfdyanshe, yes, you are right! Sorry, I didn't see it in time. @alexbarev has just pointed me to that same problem and we will submit a patch soon.
